micronaut:
  application:
    name: demo-micronaut
  router:
    static-resources:
      swagger-ui:
        mapping: /swagger-ui/**
        paths: classpath:META-INF/swagger/views/swagger-ui
      swagger:
        mapping: /swagger/**
        paths: classpath:META-INF/swagger
mongodb:
  uri: mongodb://localhost:27017/demo-micronaut
  database: demo-micronaut
  collection: users
