name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build
      run: ./gradlew build

    - name: Build Native Lambda
      run: ./gradlew buildNativeLambda

    - name: Upload lambda jar
      uses: actions/upload-artifact@v4
      with:
        name: lambda
        path: |
          build/libs/demo-micronaut-0.1-all.jar
          build/libs/demo-micronaut-0.1-lambda.zip
        retention-days: 5